version: '3'

services:

  db:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .volumes/db/sql_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: $PG_PASSWD
