version: '3'

services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - PG_PASSWD=$PG_PASSWD
      - PG_USER=$PG_USER
      - PG_DB=$PG_DB
      - PG_PORT=$PG_PORT
      - PG_HOST=db
    depends_on:
      - db

  db:
    image: postgres:9.6
    restart: always
    ports:
      - $PG_PORT:$PG_PORT
    volumes:
      - .volumes/db/sql_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: $PG_PASSWD
    healthcheck:
      test: PGPASSWORD=$PG_PASSWD psql -U $PG_USER --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"